import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "material-symbols/rounded.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import clsx from "clsx";
import ConfigureAmplifyClientSide from "@/amplify-cognito-config";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={clsx(roboto, "antialiased flex flex-col min-h-screen")}>
        <Header />
        <main className="flex-1 relative">
          <ConfigureAmplifyClientSide />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
